### PR TITLE
queries should fail when shards are missing. fixes #670

### LINKED ISSUE #670: indicate / error when cannot fully satisfy query
e.g. when there is a shard which has no up-to-date replicas (rare, but can happen when multiple nodes crash), it is impossible to accurately respond to requests. currently we just serve partial data, which can lead to misleading charts and bogus alerts.
(note to self: confirm that with one up to date replicate and one refilling, the priority system works)

### PR DESCRIPTION
**Pull request by woodsaj**
- adds config option for min-available-shards.  If the number of
  shards found in the cluster when processing a query is less then
  this number, then the query is aborted and a 503 error is returned.

### CODE REVIEW

File: api/graphite.go [hunk 1]
```diff
@@ -47,10 +47,15 @@ type Series struct {
 }
 
 func (s *Server) findSeries(orgId int, patterns []string, seenAfter int64) ([]Series, error) {
-	peers := cluster.MembersForQuery()
+	series := make([]Series, 0)
+	peers, err := cluster.MembersForQuery()
+	if err != nil {
+		log.Error(3, "HTTP findSeries unable to get peers, %s", err)
+		return series, err
```
Comment (replay) [inline api/graphite.go]: couldn't that just `return nil, err`, then you'd only have to `series := make([]Series, 0)` if there's no error.

File: cluster/config.go [hunk 2]
```diff
@@ -34,6 +35,7 @@ func ConfigSetup() {
 	clusterCfg.StringVar(&mode, "mode", "single", "Operating mode of cluster. (single|multi)")
 	clusterCfg.DurationVar(&httpTimeout, "http-timeout", time.Second*60, "How long to wait before aborting http requests to cluster peers and returning a http 503 service unavailable")
 	clusterCfg.IntVar(&maxPrio, "max-priority", 10, "maximum priority before a node should be considered not-ready.")
+	clusterCfg.IntVar(&minAvailableShards, "min-available-shards", 0, "minimum number of shards that must be available for a query to be handled.")
```
Comment (Dieterbe) [inline cluster/config.go]: why don't we make this `min-available-shards-pct` e.g. a percentage? that way if deployments get scaled up (or down), their settings will keep making sense instead of requiring to be adjusted.

File: cluster/cluster.go [hunk 3]
```diff
@@ -28,6 +30,8 @@ var (
 	Mode    ModeType
 	Manager *ClusterManager
 	cfg     *memberlist.Config
+
+	InsufficientShardsAvailable = NewError(http.StatusServiceUnavailable, fmt.Errorf("Insufficient shards available."))
```
Comment (Dieterbe) [inline cluster/cluster.go]: fmt.Errorf is good when you need to format things. If you don't, can just use `errors.New()` instead.

File: cluster/config.go (hunk 2 above)
Comment (woodsaj) [inline cluster/config.go]: No.
We don't know how many partitions there should be, we only know how many are available.
To support min-available-shards-pct we would also need to add another config variable for expected-shard-count.

Comment (Dieterbe) [inline cluster/config.go]: isn't that why all input plugins call `cluster.Manager.SetPartitions()` ?
e.g. https://github.com/raintank/metrictank/blob/master/input/kafkamdm/kafkamdm.go#L160-L165

Comment (woodsaj) [inline cluster/config.go]: that only sets the partitions for that node.  It does not give visibility into what partitions other nodes are using.
