### PR TITLE
Fix #454

### LINKED ISSUE #454: "start must be before end" when requested time range is correct
I am seeing this frequently when querying against the new 0.7.0-beta1 version of MT.

```
curl -H "X-org-id: 12574" "http://localhost:6060/render?target=metrictank.stats.ops.metrictank-read-ops-0.api.request_handle.latency.max.gauge32&from=1483795216&to=1483838416"
```
```
[Macaron] 2017-01-08 01:23:56: Started GET /render?target=metrictank.stats.ops.metrictank-read-ops-0.api.request_handle.latency.max.gauge32&from=1483795216&to=1483838416 for 127.0.0.1
2017/01/08 01:23:56 [I] HTTP Render: INCOMING REQ "GET" from: "1483795216", to: "1483838416" targets: ["metrictank.stats.ops.metrictank-read-ops-0.api.request_handle.latency.max.gauge32"], maxDataPoints: 800
2017/01/08 01:23:56 [I] oldest from aggmetrics is 1483833600
2017/01/08 01:23:56 [graphite.go:284 renderMetrics()] [E] HTTP Render start must be before end.
[Macaron] 2017-01-08 01:23:56: Completed /render?target=metrictank.stats.ops.metrictank-read-ops-0.api.request_handle.latency.max.gauge32&from=1483795216&to=1483838416 500 Internal Server Error in 582.581µs
```

As the error is intermittent is suspect it has something to do with handling partially cached data.
The error looks to be originating from:
https://github.com/raintank/metrictank/blob/master/api/dataprocessor.go#L467-L470
We should definitely log an Error here before calling panic.

this panic is handled by https://github.com/raintank/metrictank/blob/master/api/dataprocessor.go#L29
Which is why we dont get the usual stack trace.

### PR DESCRIPTION
**Pull request by replay**
I've gone through the Add/Delete/Search methods of the chunk cache one more time, with the goal of making sure that there can't be a situation where the returned `from` is > `until`, as described in #454 . 
Since I don't have enough debug data to be sure what exactly happened in #454 I can't exactly reproduce the problem and hence I can't be sure this really fixes it.

While going through the code I also found a short list of other optimizations:
- If the cache search returns a result where `from == until` we don't need to hit Cassandra. This situation can occur if the chunks are not span aware and there is a disconnect in the cache internal linked list despite the fact that all queried chunks are present (for example if insertions happened at a weird order).
- If the cache is queried for a `from == until` we can save a few ops by not even looking up whether the specified metric is present
- The `debugMetrics` method can reuse the already present `keys` slice, we don't need to rebuild it
- Saving the allocation of some variables that are not necessary
- When adding a chunk to the cache without specifying the `ts` of the previous chunk (happens if this is the first chunk of that insertion) then the `Add()` method should try to figure out if the previous chunk is present, and if it is it connects them in the internal linked list. This only works reliably if either the chunks are span aware or if the span has not changes since `> 2 * chunkSpan`
- adding more tests for chunk insertion scenarios
- the chunk cache used to keep track of the `oldest` and `newest` present chunk per metric, but these variables are not used at all, so we can drop them
- we keep regenerating the sorted list of `keys` in `CCacheMetric`, let's rather just keep it until it changes instead

### CODE REVIEW

File: mdata/cache/ccache_metric.go [hunk 1]
```diff
@@ -12,16 +12,12 @@ import (
...
-
-	// points to the timestamp of the oldest cache chunk currently held
-	// the tail of the linked list that containes the cache chunks
-	oldest uint32
-
 	// points at cached data chunks, indexed by their according time stamp
 	chunks map[uint32]*CCacheChunk
+
+	// instead of sorting the keys at each search we can save some ops by
+	// keeping the list until a chunk gets added or deleted
```
Comment (Dieterbe) [inline mdata/cache/ccache_metric.go]: this comment describes the change from previous code to new code, for which you should use the commit message. (which you already do). you should only mention here something like "maintain sorted list of chunk timestamps" or something which is more descriptive of the purpose of the variable.

File: mdata/cache/ccache_metric.go [hunk 2]
```diff
@@ -202,13 +212,13 @@ func (mc *CCacheMetric) searchBackward(from, until uint32, keys []uint32, res *C
...
+			break
+		}
+
 		log.Debug("CCacheMetric searchBackward: backward search adds chunk ts %d to end", ts)
 		res.End = append(res.End, mc.chunks[ts].Itgen)
 		res.Until = ts
-
-		if ts <= from {
-			break
-		}
```
Comment (Dieterbe) [inline mdata/cache/ccache_metric.go]: Why this change? is it related to setting prev on cache add? if yes, how so? if not, then what is this? is this a bugfix? what's the bug?

File: mdata/cache/ccache_test.go [hunk 3]
```diff
@@ -85,32 +181,32 @@ func TestSearchFromBeginningComplete(t *testing.T) {
...
 }
 
 func TestSearchFromBeginningIncompleteEnd(t *testing.T) {
 	metric := "metric1"
 	cc := getConnectedChunks(metric)
-	res := cc.Search(metric, 2500, 6000)
+	res := cc.Search(metric, 1006, 1025)
 	if !res.Complete {
-		t.Fatalf("complete is expected to be false")
+		t.Fatalf("complete is expected to be true")
```
Comment (Dieterbe) [inline mdata/cache/ccache_test.go]: what is going on here? this test has become identical to TestSearchFromBeginningComplete ? we're not testing for incomplete ends I think.

File: api/dataprocessor.go [hunk 4]
```diff
@@ -466,27 +465,25 @@ func (s *Server) getSeriesCachedStore(ctx *requestContext, until uint32) []chunk
...
+				// currently we rely on cassandra returning results in order
+				go s.Cache.Add(key, prevts, itgen)
+				prevts = itgen.Ts()
+				iters = append(iters, *it)
 			}
-			// it's important that the itgens get added in chronological order,
-			// currently we rely on cassandra returning results in order
-			go s.Cache.Add(key, prevts, itgen)
-			prevts = itgen.Ts()
-			iters = append(iters, *it)
```
Comment (Dieterbe) [inline api/dataprocessor.go]: this commit doesn't seem to have anything to do with what it claims to be about.
the actual fix somehow snuck in " figure out previous chunk on cache add" and this change is functionality identical than the previous code.

protip: use `git add -p` to add the right stuff to the right commit, and `git rebase -i` to make adjustments if needed.
in a few minutes you can set up the history in such a way that I can save many more minutes during the review process, and you'll also save minutes to anyone in the future trying to make sense of what happened to this code.

File: mdata/cache/ccache_test.go (hunk 3 above)
Comment (replay) [inline mdata/cache/ccache_test.go]: Good catch. I was only looking at this test and didn't pay attention to the one directly above!

File: api/dataprocessor.go (hunk 4 above)
Comment (replay) [inline api/dataprocessor.go]: cleaned up the history

File: mdata/cache/ccache_metric.go (hunk 2 above)
Comment (replay) [inline mdata/cache/ccache_metric.go]: That's mentioned in the last sentence of the commit message. Moving that up fixed a bug which made `searchBackward()` seek one chunk too far: https://github.com/raintank/metrictank/pull/455/commits/ecf02ee32354c6cd90e7031acc0dcc88071dd0b4

Comment (replay) [inline mdata/cache/ccache_metric.go]: I can well imagine that this is the reason for the error that @woodsaj saw. because if there is a disconnect in the linked list then it would seek to the disconnect from both sides, but the backwards one would seek one chunk too far, leading to the cassandra query receiving a `to` that's before the `from`.
